# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-chrome:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Check Node.js version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Build extension for Chrome
        run: npm run build-chrome

      - name: Check Chrome manifest.json
        run: cat ./build/chrome/manifest.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-extensions
          path: |
            ./build/chrome/**
  
  build-firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Check Node.js version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Build extension for Firefox
        run: npm run build-firefox

      - name: Check Firefox manifest.json
        run: cat ./build/firefox/manifest.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-extensions
          path: |
            ./build/firefox/**