# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    tags:        
      - '*.*.*'
  pull_request:
    branches: [ "main" ]

jobs:
  build-chrome:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Check Node.js version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Get Current Tag
        run: echo "Running on tag ${GITHUB_REF#refs/*/}"
    
      # - name: Sync manifest.json and package.json Version on Latest Tag
      #   run: npm run update-version --tag="${GITHUB_REF#refs/*/}"

      - name: Build extension for Chrome
        run: npm run build-chrome

      - name: Check Chrome manifest.json
        run: cat ./build/chrome/manifest.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-build
          path: build/chrome/**
  
  build-firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Check Node.js version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Get Current Tag
        run: echo "Running on tag ${GITHUB_REF#refs/*/}"
    
      # - name: Sync manifest.json and package.json Version on Latest Tag
      #   run: npm run update-version --tag="${GITHUB_REF#refs/*/}"

      - name: Build extension for Firefox
        run: npm run build-firefox

      - name: Check Firefox manifest.json
        run: cat ./build/firefox/manifest.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension-build
          path: build/firefox/**

  submit-chrome:
    runs-on: ubuntu-latest
    needs: build-chrome

    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension-build
          path: build/chrome

      - name: Check Chrome manifest.json
        run: cat ./build/chrome/manifest.json

      - name: Submit to Chrome Store
        env:
            EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
            CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
            REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        run: npm run submit-chrome

  submit-firefox:
    runs-on: ubuntu-latest
    needs: build-firefox

    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: firefox-extension-build
          path: build/firefox

      - name: Check Firefox manifest.json
        run: cat ./build/firefox/manifest.json

      - name: Submit to Firefox Store
        env:
            WEB_EXT_API_KEY: ${{ secrets.FIREFOX_EXT_API_KEY }}
            WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_EXT_API_SECRET }}
        run: npm run submit-firefox